export { default as Home } from './Home.js'
export { default as About } from './About.js'
export { default as Contact } from './Contact.js'
export { default as shopPage } from './shopPage.js'
export { default as GalleryPage } from './GalleryPage.js'