export { default as Home } from './Home.js'
export { default as About } from './About.js'
export { default as Contact } from './Contact.js'
export { default as ShopPage } from './ShopPage.js'
export { default as GalleryPage } from './GalleryPage.js'
